# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 17:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20171122_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='upload')),
                ('finder', models.CharField(max_length=10)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('details', models.TextField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='upload',
            name='user',
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
