# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171122_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='upload')),
                ('finder', models.CharField(max_length=10)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('details', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='IMG',
        ),
    ]
