# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20171122_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='details',
            field=models.TextField(max_length=200),
        ),
    ]
