# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171122_1621'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upload',
            new_name='UploadForm',
        ),
    ]
